# ==============================================================================
# 13_field_tables.R
# Generates: r2_3_macros.tex -- the patent-cited-share correlations, article
#            counts and number of field groups the paper quotes
# Inputs:    output/intermediate/r2_3_field_measures.csv, r2_3_correlations.csv
# ==============================================================================
source("_helpers.R")

fm <- read.csv(file.path(intermediate_dir, "r2_3_field_measures.csv"), stringsAsFactors = FALSE)
co <- read.csv(file.path(intermediate_dir, "r2_3_correlations.csv"), stringsAsFactors = FALSE)
g <- function(col, sample = "all") co[[col]][co$sample == sample]
p2 <- function(x) if (x < 0.001) "<0.001" else sprintf("%.3f", x)
write_tex(c(
  "% generated by code/13_field_tables.R -- do not edit by hand",
  mac("mRosRho",    sprintf("%+.2f", g("spearman"))),
  mac("mRosP",      p2(g("p_spearman"))),
  mac("mRosRhoSci", sprintf("%+.2f", g("spearman", "science"))),
  mac("mRosPSci",   p2(g("p_spearman", "science"))),
  mac("mRosArticlesM", sprintf("%.1f", sum(fm$ros_n_articles) / 1e6)),
  mac("mRosArticlesAllM", sprintf("%.1f", sum(fm$ros_n_articles_all) / 1e6)),
  mac("mNfields",   sprintf("%d", nrow(fm)))),
  file.path(table_dir, "r2_3_macros.tex"))
