# ==============================================================================
# 14_field_tables.R
# Generates: r2_3_macros.tex -- the numbers the paper quotes on distance to
#            application and the outside option (from script 13's CSVs)
# ==============================================================================
source("_helpers.R")

fm <- read.csv(file.path(intermediate_dir, "r2_3_field_measures.csv"), stringsAsFactors = FALSE) |>
  arrange(desc(density))
# Dentistry & Allied Health does not map onto the SDR's field options, so its pay
# is left out of the figure and the correlation alike
fm$sdr_salary_ind[fm$field == "Dentistry & Allied Health"] <- NA

co <- read.csv(file.path(intermediate_dir, "r2_3_correlations.csv"), stringsAsFactors = FALSE)
ag <- read.csv(file.path(intermediate_dir, "r2_3_proxy_agreement.csv"), row.names = 1)
g <- function(meas, col, sample = "all") co[[col]][co$measure == meas & co$sample == sample]
p2 <- function(x) if (x < 0.001) "<0.001" else sprintf("%.3f", x)
pct <- function(f, col) sprintf("%.0f", 100 * fm[[col]][fm$field == f])
indk <- function(f) sprintf("%.0f", fm$sdr_salary_ind[fm$field == f] / 1000)   # industry median, $k
n_sci <- g("ros_cited_share", "n", "science")
# window robustness of the patent-cited share: lowest rank correlation between
# the headline window's field ranking and any alternative window's
win <- read.csv(file.path(intermediate_dir, "r2_3_ros_windows.csv"), stringsAsFactors = FALSE)
base <- win[win$window == "2000-2015", c("field", "ros_cited_share")]
win_rank_min <- min(sapply(setdiff(unique(win$window), "2000-2015"), function(w) {
  x <- merge(base, win[win$window == w, c("field", "ros_cited_share")], by = "field")
  cor(x$ros_cited_share.x, x$ros_cited_share.y, method = "spearman")
}))
write_tex(c(
  "% generated by code/14_field_tables.R -- do not edit by hand",
  mac("mSdrRho",    sprintf("%+.2f", g("sdr_private_share", "spearman"))),
  mac("mSdrP",      p2(g("sdr_private_share", "p_spearman"))),
  mac("mRosRho",    sprintf("%+.2f", g("ros_cited_share", "spearman"))),
  mac("mRosP",      p2(g("ros_cited_share", "p_spearman"))),
  mac("mRosRhoSci", sprintf("%+.2f", g("ros_cited_share", "spearman", "science"))),
  mac("mRosPSci",   p2(g("ros_cited_share", "p_spearman", "science"))),
  mac("mRosRhoAll",    sprintf("%+.2f", g("ros_cited_share_all", "spearman"))),
  mac("mRosRhoGeTen",  sprintf("%+.2f", g("ros_cited_share_ge10", "spearman"))),
  mac("mRosRhoTopTenK", sprintf("%+.2f", g("ros_top10k_share", "spearman"))),
  mac("mRosRhoTopTenKSci", sprintf("%+.2f", g("ros_top10k_share", "spearman", "science"))),
  mac("mRosRhoCSeven", sprintf("%+.2f", g("ros_cited_share_c7", "spearman"))),
  mac("mRosRhoCTen",   sprintf("%+.2f", g("ros_cited_share_c10", "spearman"))),
  mac("mRosRhoFront", sprintf("%+.2f", g("ros_front_share", "spearman"))),
  mac("mRosRhoApp",   sprintf("%+.2f", g("ros_app_share", "spearman"))),
  mac("mRosRhoPerK",  sprintf("%+.2f", g("ros_pat_per_k", "spearman"))),
  mac("mRosArticlesM", sprintf("%.1f", sum(fm$ros_n_articles) / 1e6)),
  mac("mRosArticlesAllM", sprintf("%.1f", sum(fm$ros_n_articles_all) / 1e6)),
  mac("mRosMin",    sprintf("%.1f", 100 * min(fm$ros_cited_share))),
  mac("mRosMax",    sprintf("%.1f", 100 * max(fm$ros_cited_share))),
  mac("mRosTopTenKMin", sprintf("%.0f", 100 * min(fm$ros_top10k_share))),
  mac("mRosTopTenKMax", sprintf("%.0f", 100 * max(fm$ros_top10k_share))),
  mac("mRosWinRankMin", sprintf("%.2f", win_rank_min)),
  # lowest rank correlation between the headline patent-cited share and its
  # construction variants (denominators, confidence cuts, front-page only)
  mac("mRosVariantRankMin", sprintf("%.2f", min(as.matrix(ag)["ros_cited_share",
      c("ros_cited_share_all", "ros_cited_share_ge10", "ros_top5k_share", "ros_top10k_share",
        "ros_top20k_share", "ros_cited_share_c7", "ros_cited_share_c10", "ros_front_share")]))),
  mac("mRosMechAllM",  sprintf("%.0f", fm$ros_n_articles_all[fm$field == "Mechanical & Aerospace Eng."] / 1e6)),
  mac("mRosMechGeOneM", sprintf("%.1f", fm$ros_n_articles[fm$field == "Mechanical & Aerospace Eng."] / 1e6)),
  mac("mSdrRhoSci",  sprintf("%+.2f", g("sdr_private_share", "spearman", "science"))),
  mac("mNsci",       sprintf("%d", n_sci)),
  mac("mNsoc",       sprintf("%d", nrow(fm) - n_sci)),
  mac("mComteN",    sprintf("%d", sum(fm$placement == "Comte", na.rm = TRUE))),
  mac("mComteOurs", sprintf("%d", sum(fm$placement == "ours", na.rm = TRUE))),
  mac("mSdrPolsci", pct("Political Science & Sociology", "sdr_private_share")),
  mac("mSdrAnthro", pct("Anthropology", "sdr_private_share")),
  mac("mSdrChem",   pct("Chemistry & Chemical Eng.", "sdr_private_share")),
  mac("mSdrCS",     pct("Computer Science", "sdr_private_share")),
  mac("mSdrPsych",  pct("Psychology", "sdr_private_share")),
  mac("mSdrCivil",  pct("Civil & Env. Eng.", "sdr_private_share")),
  mac("mSdrMech",   pct("Mechanical & Aerospace Eng.", "sdr_private_share")),
  # pay of the industry option (SDR Table 54): median salary of doctorate
  # holders working in business or industry, $k
  mac("mIndPolsci", indk("Political Science & Sociology")),
  mac("mIndAnthro", indk("Anthropology")),
  mac("mIndChem",   indk("Chemistry & Chemical Eng.")),
  mac("mIndCS",     indk("Computer Science")),
  mac("mIndPsych",  indk("Psychology")),
  mac("mIndCivil",  indk("Civil & Env. Eng.")),
  mac("mIndMech",   indk("Mechanical & Aerospace Eng.")),
  mac("mIndRho",    sprintf("%+.2f", g("sdr_salary_ind", "spearman"))),
  mac("mIndP",      p2(g("sdr_salary_ind", "p_spearman"))),
  mac("mNfields",   sprintf("%d", nrow(fm)))),
  file.path(table_dir, "r2_3_macros.tex"))
cat("wrote r2_3_macros.tex\n")
