# ==============================================================================
# 14_pay_grouped.R
# Generates: r2_3_pay_grouped_macros.tex and r2_3_pay_grouped_scatter.pdf --
#            recognition density against the private-sector pay of a field's
#            doctorate holders (fig:fieldMeasuresB)
# Inputs:    data/ncses/pay_paper_groups.csv, data/ncses/pay_sdr_groups.csv,
#            data/vs_academics_by_finest_group.csv, winners_by_group(),
#            data/ncses/doctorate_recipients_2023.zip
#
# The paper's 26 field groups are coarsened to 16 groups that share a
# classification with the Survey of Doctorate Recipients' salary fields
# (data/ncses/pay_paper_groups.csv, pay_sdr_groups.csv). Business has no SDR
# counterpart; Dentistry & Allied Health lacks an adequate doctorate match.
#
# Salary is a survey-weighted median of individual public-use records (SDR 2023,
# data/ncses/doctorate_recipients_2023.zip): US residents, employed, private
# for-profit sector (including incorporated self-employment), working more than
# 35 hours (the public hours variable groups 21-35 hours together).
# ==============================================================================
source("_helpers.R")

paper_map <- read.csv(file.path(data_dir, "ncses/pay_paper_groups.csv"), stringsAsFactors = FALSE)
sdr_map <- read.csv(file.path(data_dir, "ncses/pay_sdr_groups.csv"), stringsAsFactors = FALSE,
                    colClasses = "character") |>
  select(NSDRMENTOD, pay_group)
stopifnot(!anyDuplicated(paper_map$field), !anyDuplicated(sdr_map$NSDRMENTOD),
          setequal(paper_map$pay_group, sdr_map$pay_group))

# Recognitions and faculty denominators from their source files
faculty <- read.csv(file.path(data_dir, "vs_academics_by_finest_group.csv"), stringsAsFactors = FALSE) |>
  filter(academic_count > 0, group_name != "Humanities") |>
  transmute(field = group_name, academic_count)
winners <- winners_by_group()
raw_density <- winners |> count(finest_group, name = "recognitions") |>
  right_join(faculty, by = c("finest_group" = "field")) |>
  transmute(field = finest_group, academic_count,
            recognitions = coalesce(recognitions, 0L))
stopifnot(!anyDuplicated(raw_density$field), nrow(raw_density) == 26L,
          setequal(setdiff(raw_density$field, paper_map$field),
                   c("Business", "Dentistry & Allied Health")))
included <- inner_join(raw_density, paper_map, by = "field")
density <- included |> group_by(pay_group) |>
  summarise(academic_count = sum(academic_count), recognitions = sum(recognitions),
            .groups = "drop") |>
  mutate(yearlyRE = recognitions / 10, density = 1000 * yearlyRE / academic_count)
stopifnot(sum(density$recognitions) == sum(included$recognitions),
          sum(density$academic_count) == sum(included$academic_count),
          nrow(density) == 16L)

archive <- file.path(data_dir, "ncses/doctorate_recipients_2023.zip")
cols <- c("NSDRMENTOD", "SALARYP", "WTSURVY", "HRSWKP", "LFSTAT", "EMSECDT", "FNINUS")
headers <- names(read.csv(unz(archive, "psd23Public/epsd23.csv"), nrows = 0))
classes <- ifelse(headers %in% cols, "character", "NULL")
micro <- read.csv(unz(archive, "psd23Public/epsd23.csv"), colClasses = classes,
                  stringsAsFactors = FALSE) |>
  mutate(across(c(SALARYP, WTSURVY, HRSWKP), as.numeric))
stopifnot(setequal(unique(micro$NSDRMENTOD), sdr_map$NSDRMENTOD),
          all(is.finite(micro$WTSURVY)), all(micro$WTSURVY > 0))
eligible <- micro |>
  filter(FNINUS == "Y", LFSTAT == "1", EMSECDT == "21", HRSWKP %in% c(3, 4))
stopifnot(all(is.finite(eligible$SALARYP)),
          all(eligible$SALARYP >= 0 & eligible$SALARYP < 9999998))
pay_records <- eligible |> left_join(sdr_map, by = "NSDRMENTOD")
stopifnot(nrow(pay_records) == nrow(eligible), !anyNA(pay_records$pay_group))
weighted_median <- function(x, w) {
  ord <- order(x)
  x[ord][which(cumsum(w[ord]) >= sum(w) / 2)[1]]
}
pay <- pay_records |> group_by(pay_group) |>
  summarise(salary = weighted_median(SALARYP, WTSURVY), .groups = "drop")
fm <- inner_join(density, pay, by = "pay_group") |> mutate(ind_k = salary / 1000)
stopifnot(nrow(fm) == nrow(density), !anyDuplicated(fm$pay_group),
          all(is.finite(fm$salary)), all(is.finite(fm$density)))
test <- cor.test(fm$salary, fm$density, method = "spearman", exact = FALSE)

write_tex(c("% generated by code/14_pay_grouped.R -- do not edit",
            sprintf("\\newcommand{\\mIndGroupedN}{%d}", nrow(fm)),
            sprintf("\\newcommand{\\mIndGroupedFields}{%d}", nrow(included)),
            sprintf("\\newcommand{\\mIndGroupedRho}{%+.2f}", test$estimate),
            sprintf("\\newcommand{\\mIndGroupedP}{%.3f}", test$p.value)),
          file.path(table_dir, "r2_3_pay_grouped_macros.tex"))

labels <- c("Agriculture & Environmental Sci." = "Agriculture &\nEnvironmental Sci.",
            "Other Biological & Health Sci." = "Other Biological\n& Health Sci.",
            "Anthropology & Other Social Sci." = "Anthropology &\nOther Social Sci.",
            "Mechanical & Aerospace Eng." = "Mechanical &\nAerospace Eng.",
            "Computer & Electrical Eng." = "Computer &\nElectrical Eng.",
            "Political Science & Sociology" = "Political Science\n& Sociology",
            "Microbiology & Immunology" = "Microbiology &\nImmunology",
            "Chemistry & Chemical Eng." = "Chemistry &\nChemical Eng.",
            "Biomedical & Other Eng." = "Biomedical &\nOther Eng.")
fm$plot_label <- ifelse(fm$pay_group %in% names(labels), labels[fm$pay_group], fm$pay_group)
p <- ggplot(fm, aes(ind_k, density)) +
  geom_smooth(method = "lm", se = FALSE, color = "#CBC3E3", linewidth = 0.5) +
  geom_point(shape = 21, size = 2, fill = "blue", alpha = 0.6) +
  geom_label_repel(aes(label = plot_label), box.padding = 0.2, point.padding = 0.3,
                   min.segment.length = 0, force = 15, max.overlaps = Inf,
                   segment.color = "grey50", segment.size = 0.4, segment.alpha = 0.6,
                   fill = alpha("white", 0.7), label.size = NA, size = 2.3,
                   lineheight = 0.9, seed = 1, max.time = 5, max.iter = 1e5) +
  scale_x_continuous(labels = function(x) paste0("$", x, "k"), expand = expansion(mult = c(.12, .12))) +
  scale_y_continuous(expand = expansion(mult = c(.08, .1))) +
  labs(x = "Median Annual Private-Sector Salary",
       y = "Recognitions per 1,000 Top Researchers") +
  theme_minimal() +
  theme(panel.background = element_rect(fill = "white", color = NA),
        plot.background = element_rect(fill = "white", color = NA),
        panel.grid.minor = element_blank(), panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(color = "black", linewidth = 0.1))
save_figure("r2_3_pay_grouped_scatter.pdf", p, width = 6, height = 3.8)
