# ==============================================================================
# 18_home_bias_tables.R
# Produces r2_2_macros.tex (home-bias numbers quoted in the Discussion, top-1,000
# benchmark), r2_2_macros_share01.tex / r2_2_macros_share005.tex (the
# actual-to-expected ratio under the top-0.1% / top-0.05% benchmarks, quoted in
# the notes of r2_2_prize_table.tex) and r2_2_prize_table.tex (tab:r2_2_prizes:
# prizes with the largest home-bias excess).
# Inputs (output/intermediate/, script 17): r2_2_winner_countries.csv,
# r2_2_home_awards_by_country{,_share01,_share005}.csv, r2_2_prize_home_bias.csv
# ==============================================================================
source("_helpers.R")

POOL_DESC <- "the field's 1{,}000 researchers with the most citations to small-team papers"
esc <- function(x) gsub("&", "\\\\&", x)
sgn <- function(v, digits = 1) sprintf("$%s$%.*f", ifelse(v >= 0, "+", "-"), digits, abs(v))

wc <- read.csv(file.path(intermediate_dir, "r2_2_winner_countries.csv"), stringsAsFactors = FALSE, encoding = "UTF-8")
yr <- range(wc$Year, na.rm = TRUE)

# benchmark-pool file suffix and the suffix appended to its macro names
RUNS <- list(list(sfx = "", msfx = ""),
             list(sfx = "_share005", msfx = "ShareHalf"),
             list(sfx = "_share01", msfx = "ShareOne"))

for (run in RUNS) {
  cty <- read.csv(file.path(intermediate_dir, paste0("r2_2_home_awards_by_country", run$sfx, ".csv")),
                  stringsAsFactors = FALSE, encoding = "UTF-8")
  actual <- sum(cty$actual); expected <- sum(cty$expected)
  m <- function(k, v) mac(paste0(k, run$msfx), v)
  ratio_mac <- m("hbRatio", sprintf("%.2f", actual / expected))

  # ---- main benchmark: prize-level extremes and every headline number ----
  if (run$sfx == "") {
    ps <- read.csv(file.path(intermediate_dir, "r2_2_prize_home_bias.csv"),
                   stringsAsFactors = FALSE, encoding = "UTF-8") |>
      filter(!is.na(excess_pop))
    prow <- function(r) sprintf("%s & %s & %d & %.2f & %.2f & %s \\\\",
                                esc(r$Prize), esc(r$AwardingCountry), r$n_winners,
                                r$home_share, r$benchmark_pop, sgn(r$excess_pop, 2))
    top <- ps |> arrange(desc(excess_pop)) |> head(10)
    bot <- ps |> arrange(excess_pop) |> head(4)
    prize_notes <- sprintf(paste0(
      "Benchmark: %s, located by their affiliations up to the award year (see the ",
      "supplementary home-bias figures). $N$ is the number of %d--%d recognitions; the ",
      "smallest $N$ are noisy. Home and Bench.\\ are the shares of the prize's laureates and ",
      "of the benchmark researchers based in the awarding country; Excess is their difference. ",
      "The results are robust to benchmark size: benchmarks of the top 0.1\\%% or 0.05\\%% of ",
      "each field's cited authors, so that benchmark size scales with field size, give ",
      "actual-to-expected domestic recognition ratios of \\hbRatioShareOne$\\times$ and ",
      "\\hbRatioShareHalf$\\times$, against \\hbRatio$\\times$ for the top-1{,}000 benchmark."),
      POOL_DESC, yr[1], yr[2])
    write_tex(c(
      "% generated by code/18_home_bias_tables.R -- do not edit by hand",
      "\\begin{table}[H]", "\\centering \\small",
      "\\caption{Prizes with the Largest Home-Bias Excess Against the Field Benchmark}",
      "\\label{tab:r2_2_prizes}",
      "\\scalebox{0.8}{%",
      "\\begin{tabular}{llrrrr}", "\\toprule",
      "Prize & Country & $N$ & Home & Bench. & Excess \\\\", "\\midrule",
      vapply(seq_len(nrow(top)), function(i) prow(top[i, ]), character(1)),
      "\\midrule", "\\multicolumn{6}{l}{\\emph{Largest negative excess:}} \\\\",
      vapply(seq_len(nrow(bot)), function(i) prow(bot[i, ]), character(1)),
      "\\bottomrule", "\\end{tabular}", "}",
      "\\par\\vspace{3pt}", "\\begin{minipage}{0.8\\linewidth}\\footnotesize",
      paste0("\\textit{Note}: ", prize_notes),
      "\\end{minipage}", "\\end{table}"),
      file.path(table_dir, "r2_2_prize_table.tex"))

    macros <- c(
      m("hbRecognitions", formatC(sum(cty$n_awards), big.mark = "{,}", format = "d")),
      m("hbActual", actual),
      m("hbExpected", sprintf("%.0f", expected)),
      ratio_mac,
      m("hbRatioPct", sprintf("%.0f", 100 * (actual / expected - 1))),
      m("hbNPrizes", nrow(ps)),
      m("hbShareAbove", sprintf("%.1f", 100 * mean(ps$excess_pop > 0, na.rm = TRUE))),
      # per-country ratios quoted in the text (actual / expected recognitions to locals)
      unlist(lapply(c(JP = "Japan", US = "United States"), function(cn) {
        r <- cty[cty$AwardingCountry == cn, ]
        m(paste0("hbRatio", gsub(" ", "", cn)), sprintf("%.1f", r$actual / r$expected))
      })))
  } else {
    macros <- ratio_mac
  }
  write_tex(c("% generated by code/18_home_bias_tables.R -- do not edit by hand", macros),
            file.path(table_dir, paste0("r2_2_macros", run$sfx, ".tex")))
}
