# ==============================================================================
# 19_home_bias_tables.R
# Generates, from script 18's intermediate files:
#   r2_2_macros.tex, r2_2_macros_share01.tex, r2_2_macros_share005.tex
#       headline home-bias numbers for the main pool and the two robustness pools
#   r2_2_prize_table.tex  (Table S10: prizes with the largest home-bias excess)
# ==============================================================================
source("_helpers.R")

POOL_DESC <- "the field's 1{,}000 researchers with the most citations to small-team papers"
esc <- function(x) gsub("&", "\\\\&", x)
sgn <- function(v, digits = 1) sprintf("$%s$%.*f", ifelse(v >= 0, "+", "-"), digits, abs(v))

wc <- read.csv(file.path(intermediate_dir, "r2_2_winner_countries.csv"), stringsAsFactors = FALSE, encoding = "UTF-8")
yr <- range(wc$Year, na.rm = TRUE)

# pool file suffix -> macro-name suffix, so the three sets can be input together
RUNS <- list(list(sfx = "", msfx = ""),
             list(sfx = "_share005", msfx = "ShareHalf"),
             list(sfx = "_share01", msfx = "ShareOne"))

for (run in RUNS) {
  cty <- read.csv(file.path(intermediate_dir, paste0("r2_2_home_awards_by_country", run$sfx, ".csv")),
                  stringsAsFactors = FALSE, encoding = "UTF-8") |>
    arrange(desc(excess_awards))
  ps <- read.csv(file.path(intermediate_dir, paste0("r2_2_prize_home_bias", run$sfx, ".csv")),
                 stringsAsFactors = FALSE, encoding = "UTF-8") |>
    filter(!is.na(excess_pop))

  # ---- prize-level extremes (main pool only) ----
  if (run$sfx == "") {
    prow <- function(r) sprintf("%s & %s & %d & %.2f & %.2f & %s \\\\",
                                esc(r$Prize), esc(r$AwardingCountry), r$n_winners,
                                r$home_share, r$benchmark_pop, sgn(r$excess_pop, 2))
    top <- ps |> arrange(desc(excess_pop)) |> head(10)
    bot <- ps |> arrange(excess_pop) |> head(4)
    write_tex(c(
      "% generated by code/19_home_bias_tables.R -- do not edit by hand",
      "\\begin{table}[H]", "\\centering \\small",
      sprintf(paste0("\\caption{Prizes with the largest home-bias excess against the ",
                     "field benchmark (", POOL_DESC, "). $N$ is the number of %d--%d recognitions; ",
                     "the smallest $N$ are noisy.}"), yr[1], yr[2]),
      "\\label{tab:r2_2_prizes}",
      "\\begin{tabular}{llrrrr}", "\\toprule",
      "Prize & Country & $N$ & Home & Bench. & Excess \\\\", "\\midrule",
      vapply(seq_len(nrow(top)), function(i) prow(top[i, ]), character(1)),
      "\\midrule", "\\multicolumn{6}{l}{\\emph{Largest negative excess:}} \\\\",
      vapply(seq_len(nrow(bot)), function(i) prow(bot[i, ]), character(1)),
      "\\bottomrule", "\\end{tabular}", "\\end{table}"),
      file.path(table_dir, "r2_2_prize_table.tex"))
  }

  # ---- headline numbers as macros ----
  n_rec <- sum(cty$n_awards); actual <- sum(cty$actual)
  expected <- sum(cty$expected); expected_c10 <- sum(cty$expected_c10)
  m <- function(k, v) mac(paste0(k, run$msfx), v)
  write_tex(c(
    "% generated by code/19_home_bias_tables.R -- do not edit by hand",
    m("hbRecognitions", formatC(n_rec, big.mark = "{,}", format = "d")),
    m("hbActual", actual),
    m("hbExpected", sprintf("%.0f", expected)),
    m("hbExcess", sprintf("%.0f", actual - expected)),
    m("hbRatio", sprintf("%.2f", actual / expected)),
    m("hbRatioPct", sprintf("%.0f", 100 * (actual / expected - 1))),
    m("hbActualPct", sprintf("%.1f", 100 * actual / n_rec)),
    m("hbExpectedPct", sprintf("%.1f", 100 * expected / n_rec)),
    m("hbRatioWidePool", sprintf("%.1f", actual / expected_c10)),
    m("hbNPrizes", nrow(ps)),
    m("hbNoHome", 99 - nrow(ps)),
    m("hbMeanHome", sprintf("%.1f", 100 * mean(ps$home_share))),
    m("hbMeanBench", sprintf("%.1f", 100 * mean(ps$benchmark_pop, na.rm = TRUE))),
    m("hbMeanExcess", sprintf("%.1f", 100 * mean(ps$excess_pop, na.rm = TRUE))),
    m("hbMedianExcess", sprintf("%.1f", 100 * median(ps$excess_pop, na.rm = TRUE))),
    m("hbShareAbove", sprintf("%.1f", 100 * mean(ps$excess_pop > 0, na.rm = TRUE))),
    m("hbYearFirst", yr[1]), m("hbYearLast", yr[2]),
    # per-country ratios quoted in the text (actual / expected recognitions to locals)
    unlist(lapply(c(JP = "Japan", IL = "Israel", IT = "Italy", DE = "Germany", US = "United States", GB = "United Kingdom",
                    SE = "Sweden", NO = "Norway", HK = "Hong Kong"), function(cn) {
      r <- cty[cty$AwardingCountry == cn, ]
      if (nrow(r) == 0) return(character(0))
      m(paste0("hbRatio", gsub(" ", "", cn)), sprintf("%.1f", r$actual / r$expected))
    }))
  ), file.path(table_dir, paste0("r2_2_macros", run$sfx, ".tex")))
}
cat("wrote r2_2_macros{,_share005,_share01}.tex and r2_2_prize_table.tex\n")
