# ==============================================================================
# 20_teams.R
# Generates: r2_6_macros.tex -- number of recognition events in the 2015-2024
#            panel, mean laureates per event, and the number of prizes that
#            never split an award
# Inputs:    data/all_winners_with_plotFinestField.csv
# ==============================================================================
source("_helpers.R")

w <- read.csv(file.path(data_dir, "all_winners_with_plotFinestField.csv"),
              check.names = FALSE, stringsAsFactors = FALSE, encoding = "UTF-8")
# One row per laureate; a collaboration award (EHT 2020, Oxford-AstraZeneca 2022)
# is one row, the person who accepted it.
ev <- w |> group_by(Prize, Year) |> summarise(n = n(), .groups = "drop")
per_prize <- ev |> group_by(Prize) |> summarise(max_n = max(n), .groups = "drop")

write_tex(c(
  "% generated by code/20_teams.R -- do not edit by hand",
  mac("tEvents", nrow(ev)), mac("tMeanLaur", sprintf("%.1f", mean(ev$n))),
  mac("tPrizesSolo", sum(per_prize$max_n == 1))
), file.path(table_dir, "r2_6_macros.tex"))
