"""21_recipients_by_prestige.py

Generates r2_6_prestige_macros.tex: the Pearson correlation, and its p-value,
between a prize's prestige index (pcaRatingNorm, the PCA index with the Nobel
Prize in Physics = 100) and its mean number of laureates per award over
2015-2024 in the winners panel.

Inputs  data/all_winners_with_plotFinestField.csv, data/cleanPrizeList.xlsx
Run from the repository root.
"""
import os
import re
import unicodedata

import pandas as pd
from scipy import stats

DATA = "data"
TABLES = os.path.join("output", "tables")

TITLE_XWALK = {
    "balzan prize": "balzan prizes",
    "gold medal of the royal astronomical society": "gold medal for astronomy",
}


def norm(s):
    s = unicodedata.normalize("NFKD", str(s).strip())
    s = "".join(c for c in s if not unicodedata.combining(c))
    s = re.sub(r"[‐-―]", "-", s)
    s = re.sub(r"\s+", " ", s).lower()
    return TITLE_XWALK.get(s, s)


# ---- recipients per award ----
w = pd.read_csv(os.path.join(DATA, "all_winners_with_plotFinestField.csv"), encoding="utf-8")
ev = w.groupby(["Prize", "Year"]).size().reset_index(name="n")
pp = ev.groupby("Prize").agg(mean_n=("n", "mean")).reset_index()
pp["key"] = pp["Prize"].map(norm)

# ---- prestige ----
pl = pd.read_excel(os.path.join(DATA, "cleanPrizeList.xlsx"))
pl.columns = [str(c).replace(" ", "") for c in pl.columns]
pl["key"] = pl["AwardName"].map(norm)
pl = pl[["key", "pcaRatingNorm"]]

d = pp.merge(pl, on="key", how="left")
if d.pcaRatingNorm.isna().any():
    raise ValueError("prizes in the winners panel not matched to the prestige index: %s"
                     % list(d.loc[d.pcaRatingNorm.isna(), "Prize"]))

# ---- Pearson correlation of prestige and recipients per award ----
r, pr = stats.pearsonr(d.pcaRatingNorm, d.mean_n)


def mac(name, val):
    return "\\newcommand{\\%s}{%s}\n" % (name, val)


with open(os.path.join(TABLES, "r2_6_prestige_macros.tex"), "w", encoding="utf-8", newline="\n") as f:
    f.write("%% generated by code/21_recipients_by_prestige.py -- do not edit by hand\n")
    f.write(mac("pgR", "%+.2f" % r))
    # carries the comparison operator: the paper writes $p\pgP$
    f.write(mac("pgP", "<0.01" if pr < 0.01 else "=%.2f" % pr))
print("wrote r2_6_prestige_macros.tex")
