# ==============================================================================
# 21_teams.R
# Generates: r2_6_macros.tex -- laureates per recognition event in the 2015-2024
#            panel (how many prizes ever split an award, among how many people,
#            how many events went to an organization), and the long-run Nobel
#            record (physics, chemistry, medicine, economics; laureates per award
#            and the share of awards shared, 1901-2025, from the Nobel Foundation
#            API responses cached in data/nobel_api_cache.json)
# ==============================================================================
source("_helpers.R")

# ---- A. the 99-prize panel, 2015-2024 ----
w <- read.csv(file.path(data_dir, "all_winners_with_plotFinestField.csv"),
              check.names = FALSE, stringsAsFactors = FALSE, encoding = "UTF-8")
# Laureates per award count the people the awarding body named; the two
# collaboration awards (EHT 2020, Oxford-AstraZeneca 2022) count as the person
# who accepted them. n_winners keeps the recorded roster (EHT 347).
ev <- w |> group_by(Prize, Year) |> summarise(n = n(), .groups = "drop")
ev_ind <- w |> filter(laureate_type == "individual") |>
  group_by(Prize, Year) |> summarise(n = n(), .groups = "drop")
by_year <- ev |> group_by(Year) |>
  summarise(events = n(), mean_laureates = mean(n), share_shared = mean(n >= 2),
            share_three_plus = mean(n >= 3), .groups = "drop")
per_prize <- ev |> group_by(Prize) |> summarise(max_n = max(n), .groups = "drop")
org <- w |> filter(laureate_type == "collaboration")
cat("== 99-prize panel 2015-2024 ==\n")
cat("recognition events:", nrow(ev), " mean laureates/event:", round(mean(ev$n), 2),
    " shared:", sprintf("%.0f%%", 100 * mean(ev$n >= 2)),
    " three-plus:", sprintf("%.0f%%", 100 * mean(ev$n >= 3)), "\n")

# ---- B. the Nobel record ----
nob <- fromJSON(file.path(data_dir, "nobel_api_cache.json"), simplifyVector = FALSE)
nd <- bind_rows(lapply(nob, function(p) {
  data.frame(year = as.integer(p$awardYear), category = p$category$en,
             n = length(p$laureates %||% list()), stringsAsFactors = FALSE)
})) |> filter(n > 0)                                   # drop years not awarded
allsci <- nd |> filter(category != "Economic Sciences")
early <- allsci |> filter(year <= 1930); late <- allsci |> filter(year >= 2010)
cat("\n== Nobel science prizes (physics, chemistry, medicine) ==\n")
cat("1901-1930: awards", nrow(early), " mean laureates", round(mean(early$n), 2),
    " shared", sprintf("%.0f%%", 100 * mean(early$n >= 2)), "\n")
cat("2010-2025: awards", nrow(late), " mean laureates", round(mean(late$n), 2),
    " shared", sprintf("%.0f%%", 100 * mean(late$n >= 2)),
    " at the three-person cap", sprintf("%.0f%%", 100 * mean(late$n >= 3)), "\n")

write_tex(c(
  "% generated by code/21_teams.R -- do not edit by hand",
  mac("tEvents", nrow(ev)), mac("tMeanLaur", sprintf("%.1f", mean(ev$n))),
  # the same statistics with the two collaboration events left out entirely
  mac("tEventsExclTeams", nrow(ev_ind)), mac("tMeanLaurExclTeams", sprintf("%.2f", mean(ev_ind$n))),
  mac("tRecsPerYear", sprintf("%.0f", sum(ev$n) / 10)),
  mac("tCollabEvents", sum(w$laureate_type == "collaboration", na.rm = TRUE)),
  mac("tTeamSizeEHT", max(w$n_winners, na.rm = TRUE)),
  mac("tShareShared", sprintf("%.0f", 100 * mean(ev$n >= 2))),
  mac("tShareThree", sprintf("%.0f", 100 * mean(ev$n >= 3))),
  mac("tMeanFirst", sprintf("%.2f", by_year$mean_laureates[by_year$Year == min(by_year$Year)])),
  mac("tMeanLast", sprintf("%.2f", by_year$mean_laureates[by_year$Year == max(by_year$Year)])),
  mac("tPrizesSolo", sum(per_prize$max_n == 1)), mac("tPrizesMaxTwo", sum(per_prize$max_n == 2)),
  mac("tPrizesMaxThree", sum(per_prize$max_n == 3)), mac("tPrizesFourPlus", sum(per_prize$max_n >= 4)),
  mac("tOrgLaureates", nrow(org)),
  mac("tNobelEarlyMean", sprintf("%.1f", mean(early$n))),
  mac("tNobelEarlyShared", sprintf("%.0f", 100 * mean(early$n >= 2))),
  mac("tNobelLateMean", sprintf("%.1f", mean(late$n))),
  mac("tNobelLateShared", sprintf("%.0f", 100 * mean(late$n >= 2))),
  mac("tNobelLateCap", sprintf("%.0f", 100 * mean(late$n >= 3)))
), file.path(table_dir, "r2_6_macros.tex"))
cat("\nwrote r2_6_macros.tex\n")
