"""22_ec_summary.py

Writes r2_9_ec_macros.tex: the early-career list's recognition events per year
(total and relative to the main list), median daily Wikipedia page views of the
early-career and main lists, mathematics' share of early-career prizes and
events, the events accounted for by the Sloan Research Fellowship and by the
five cohort programmes (Sloan, the three Otto Hahn Medal sections, Amelia
Earhart Fellowship), and the number of prizes recognizing at most one person a
year. Writes r2_9_ec_stage_macros.tex: the share of early-career prizes whose
eligibility rule targets students and the share targeting postdocs.
Inputs: data/cleanEC.xlsx (68 prizes, humanities excluded),
data/cleanPrizeList.xlsx (99 prizes) and data/r2_9_ec_stage_by_prize.csv,
whose events_corrected column gives each early-career prize's yearly recognition
events: observed 2015-2024 counts for the 14 prizes whose recipients were
collected, 10 a year for each Otto Hahn Medal section (30 in total), 0.6 for
the LTPP Challenge category (awarded in 6 of the 10 years), and the list's
estimate otherwise; and whose stage_code column gives the career stage the
prize's eligibility rule targets (student / postdoc / faculty / nonresearcher /
unknown), coded from the awarding body's rule text. Run from the repository root.
"""
import os

import pandas as pd

DATA = "data"
TABLES = os.path.join("output", "tables")

ec = pd.read_excel(os.path.join(DATA, "cleanEC.xlsx"))
ec = ec[ec["Field"] != "Humanities"].reset_index(drop=True)
main = pd.read_excel(os.path.join(DATA, "cleanPrizeList.xlsx"))

audit = pd.read_csv(os.path.join(DATA, "r2_9_ec_stage_by_prize.csv")).set_index("Award Name", verify_integrity=True)
assert len(ec) == 68 and set(ec["Award Name"]) == set(audit.index)
audit = audit.loc[ec["Award Name"]]
counts = audit["events_corrected"].to_numpy()
ec["Yearly Winners"] = counts

yw = ec["Yearly Winners"]
total_ec = yw.sum()
total_main = main["Yearly Winners"].sum()

# Large-cohort programmes: Sloan, the three Otto Hahn sections, Amelia Earhart.
bulk = ec["Award Name"].str.contains("Sloan|Otto Hahn|Amelia Earhart", regex=True)
sloan = ec["Award Name"].str.contains("Sloan")

# Visibility. The early-career list uses "effective views" (page views net of
# shared pages); the main list uses "Daily Page Views". Both are daily Wikipedia
# page views.
ec_views = ec["effective views"]
main_views = main["Daily Page Views"]
main_median_views = main_views.median()

math = ec["Field"] == "Mathematics"

mac = lambda k, v: "\\newcommand{\\rTwoNineEc%s}{%s}" % (k, v)
pct = lambda x: "%.0f" % (100 * x)
lines = [
    "% generated by code/22_ec_summary.py -- do not edit by hand",
    mac("EventsYr", "%.0f" % total_ec),
    mac("EventsRatio", "%.1f" % (total_ec / total_main)),
    mac("MedianViews", "%.1f" % ec_views.median()),
    mac("MainMedianViews", "%.1f" % main_median_views),
    mac("MathPrizesPct", pct(math.mean())),
    mac("MathEventsPct", pct(yw[math].sum() / total_ec)),
    mac("SloanYr", "%.0f" % yw[sloan].sum()),
    mac("SloanPct", pct(yw[sloan].sum() / total_ec)),
    mac("BulkPct", pct(yw[bulk].sum() / total_ec)),
    mac("SingleWinner", int((yw <= 1).sum())),
]
with open(os.path.join(TABLES, "r2_9_ec_macros.tex"), "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines) + "\n")

# Career stage targeted by the eligibility rule: share of the 68 prizes.
stage_lines = ["% generated by code/22_ec_summary.py -- do not edit by hand"]
for stage, key in (("student", "Student"), ("postdoc", "Postdoc")):
    stage_lines.append(mac("StageCorr%sPrizesPct" % key, pct((audit["stage_code"] == stage).mean())))
with open(os.path.join(TABLES, "r2_9_ec_stage_macros.tex"), "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(stage_lines) + "\n")
