"""22_recipients_by_prestige.py

Generates r2_6_prestige_macros.tex: do more prestigious prizes recognize more or
fewer people per award? Prestige is pcaRatingNorm, the paper's PCA index anchored
so the Nobel Prize in Physics = 100; recipients are the mean laureates per award
over 2015-2024 from the winners panel. The relationship is measured three ways
(Pearson, Spearman, and a comparison of the top and bottom prestige tertiles),
since the mean recipient count is right-skewed and bounded below at 1.

Inputs  data/all_winners_with_plotFinestField.csv, data/cleanPrizeList.xlsx
Run from the repository root.
"""
import os
import re
import unicodedata

import pandas as pd
from scipy import stats

DATA = "data"
TABLES = os.path.join("output", "tables")

TITLE_XWALK = {
    "balzan prize": "balzan prizes",
    "gold medal of the royal astronomical society": "gold medal for astronomy",
}


def norm(s):
    s = unicodedata.normalize("NFKD", str(s).strip())
    s = "".join(c for c in s if not unicodedata.combining(c))
    s = re.sub(r"[‐-―]", "-", s)
    s = s.replace("&", "and").replace("BBVA Foundation", "").strip()
    s = re.sub(r"\s+", " ", s).lower()
    return TITLE_XWALK.get(s, s)


# ---- recipients per award ----
w = pd.read_csv(os.path.join(DATA, "all_winners_with_plotFinestField.csv"), encoding="utf-8")
ev = w.groupby(["Prize", "Year"]).size().reset_index(name="n")
pp = ev.groupby("Prize").agg(events=("n", "size"), mean_n=("n", "mean"), max_n=("n", "max")).reset_index()
pp["key"] = pp["Prize"].map(norm)

# ---- prestige ----
pl = pd.read_excel(os.path.join(DATA, "cleanPrizeList.xlsx"))
pl.columns = [str(c).replace(" ", "") for c in pl.columns]
pl["key"] = pl["AwardName"].map(norm)
pl = pl[["key", "pcaRatingNorm", "pcaRank"]].drop_duplicates("key")

d = pp.merge(pl, on="key", how="left")
print("prizes: %d | matched to prestige index: %d" % (len(d), d.pcaRatingNorm.notna().sum()))
if d.pcaRatingNorm.isna().any():
    print("UNMATCHED:", list(d.loc[d.pcaRatingNorm.isna(), "Prize"]))
d = d.dropna(subset=["pcaRatingNorm"]).copy()

# ---- the relationship, three ways ----
r, pr = stats.pearsonr(d.pcaRatingNorm, d.mean_n)
rho, prho = stats.spearmanr(d.pcaRatingNorm, d.mean_n)
d["tier"] = pd.qcut(d.pcaRatingNorm, 3, labels=["bottom third", "middle third", "top third"])
hi = d.loc[d.tier == "top third", "mean_n"]
lo = d.loc[d.tier == "bottom third", "mean_n"]
tt = stats.ttest_ind(hi, lo, equal_var=False)
print("Pearson  r   = %+.3f (p=%.3f)" % (r, pr))
print("Spearman rho = %+.3f (p=%.3f)" % (rho, prho))
print("top third vs bottom third: %+.2f recipients (Welch p=%.3f)" % (hi.mean() - lo.mean(), tt.pvalue))


def mac(name, val):
    assert name.isalpha(), name
    return "\\newcommand{\\%s}{%s}\n" % (name, val)


with open(os.path.join(TABLES, "r2_6_prestige_macros.tex"), "w", encoding="utf-8", newline="\n") as f:
    f.write("%% generated by code/22_recipients_by_prestige.py -- do not edit by hand\n")
    f.write(mac("pgR", "%+.2f" % r))
    f.write(mac("pgP", "%.2f" % pr))
    f.write(mac("pgRho", "%+.2f" % rho))
    f.write(mac("pgTopThird", "%.2f" % hi.mean()))
    f.write(mac("pgBotThird", "%.2f" % lo.mean()))
    f.write(mac("pgTierP", "%.2f" % tt.pvalue))
print("wrote r2_6_prestige_macros.tex")
