"""23_ec_summary.py

Generates r2_9_ec_macros.tex: what the early-career prize list shows (the
Career-stages results). Three facts, computed from the cleaned early-career list
(data/cleanEC.xlsx, humanities prizes dropped, 68 prizes) and the main list
(data/cleanPrizeList.xlsx, 99 prizes):

  1. Scarcity at the top: the early-career list is thin in prestige. Its median
     prize has a fraction of the online visibility of the median main-list
     prize, and only a handful would clear the main list's Wikipedia bar.
  2. Concentration in mathematics at the top of the early-career ranking.
  3. Volume at low prestige each: the 68 prizes generate more recognition events
     per year than the 99 main prizes, driven by a few large-cohort programmes.

Tiers follow the main ranking table: after dropping humanities prizes, the first
ten by rank are Tier 1, the next twenty Tier 2. Yearly recognition counts use
the observed counts of data/r2_9_ec_stage_by_prize.csv (a 14-prize collection of
actual 2020-2024 recipients, Otto Hahn's 30/year ceiling split across its three
sections, and a frequency correction); the other prizes keep the list's estimates.
Run from the repository root.
"""
import os

import pandas as pd

DATA = "data"
TABLES = os.path.join("output", "tables")

ec = pd.read_excel(os.path.join(DATA, "cleanEC.xlsx"))
ec = ec[ec["Field"] != "Humanities"].sort_values("Rank").reset_index(drop=True)
ec["Tier"] = 3
ec.loc[:9, "Tier"] = 1
ec.loc[10:29, "Tier"] = 2
main = pd.read_excel(os.path.join(DATA, "cleanPrizeList.xlsx"))

original_total_ec = ec["Yearly Winners"].sum()
audit = pd.read_csv(os.path.join(DATA, "r2_9_ec_stage_by_prize.csv")).set_index("Award Name", verify_integrity=True)
assert len(ec) == 68 and set(ec["Award Name"]) == set(audit.index)
audit = audit.loc[ec["Award Name"]]
assert (abs(audit["events_prior"].to_numpy() - ec["Yearly Winners"].to_numpy()) < 1e-8).all()
counts = audit["events_corrected"].to_numpy()
assert pd.notna(counts).all() and (counts >= 0).all()
assert abs(counts[ec["Award Name"].str.contains("Otto Hahn").to_numpy()].sum() - 30) < 1e-8
ec["Yearly Winners"] = counts

yw = ec["Yearly Winners"]
total_ec = yw.sum()
total_main = main["Yearly Winners"].sum()

# Large-cohort programmes: Sloan, the three Otto Hahn sections, Amelia Earhart.
bulk = ec["Award Name"].str.contains("Sloan|Otto Hahn|Amelia Earhart", regex=True)
sloan = ec["Award Name"].str.contains("Sloan")
in_main = ec["Award Name"].isin(main["Award Name"]) | ec["Award Name"].str.contains(
    "Fields Medal|ICTP Ramanujan|Max Planck-Humboldt", regex=True)

# Visibility. The early-career list uses "effective views" (page views net of
# shared pages); the main list uses "Daily Page Views". Both are daily Wikipedia
# page views.
ec_views = ec["effective views"]
main_views = main["Daily Page Views"]
main_median_views = main_views.median()
# The main list's Wikipedia bar (criterion 4) is the lowest page-view count among
# prizes flagged C4.
c4 = main["C4"].notna() & (main["C4"].astype(str).str.strip() != "")
wiki_bar = main.loc[c4, "Daily Page Views"].min()

t1 = ec[ec["Tier"] == 1]
t12 = ec[ec["Tier"] <= 2]
math = ec["Field"] == "Mathematics"

by_field = (ec.assign(events=yw)
            .groupby("Field")
            .agg(prizes=("Award Name", "size"), events_per_year=("events", "sum"))
            .sort_values("events_per_year", ascending=False))
by_field["events_share_pct"] = by_field["events_per_year"] / total_ec * 100

mac = lambda k, v: "\\newcommand{\\rTwoNineEc%s}{%s}" % (k, v)
pct = lambda x: "%.0f" % (100 * x)
lines = [
    "% generated by code/23_ec_summary.py -- do not edit by hand",
    "% Count basis: audited; uncollected prizes still use estimates.",
    mac("OriginalEventsYr", "%.0f" % original_total_ec),
    mac("Prizes", len(ec)),
    mac("EventsYr", "%.0f" % total_ec),
    mac("MainEventsYr", "%.0f" % total_main),
    mac("EventsRatio", "%.1f" % (total_ec / total_main)),
    mac("InMain", int(in_main.sum())),
    # 1. prestige is thin
    mac("MedianViews", "%.1f" % ec_views.median()),
    mac("MainMedianViews", "%.1f" % main_median_views),
    mac("ViewsRatio", "%.0f" % (main_median_views / ec_views.median())),
    mac("AboveMainMedian", int((ec_views > main_median_views).sum())),
    mac("ClearWikiBar", int((ec_views >= wiki_bar).sum())),
    mac("ClearWikiBarNotMain", int(((ec_views >= wiki_bar) & ~in_main).sum())),
    mac("WikiBar", "%.0f" % wiki_bar),
    mac("FieldsToSecond", "%.0f" % (ec_views.iloc[0] / ec_views.iloc[1])),
    mac("MedianAge", "%.0f" % ec["prize age"].median()),
    mac("MainMedianAge", "%.0f" % main["age"].median()),
    # 2. mathematics at the top
    mac("TierOneMath", int((t1["Field"] == "Mathematics").sum())),
    mac("TierOneN", len(t1)),
    mac("TierOneTwoMath", int((t12["Field"] == "Mathematics").sum())),
    mac("TierOneTwoN", len(t12)),
    mac("MathPrizes", int(math.sum())),
    mac("MathPrizesPct", pct(math.mean())),
    mac("MathEventsPct", pct(yw[math].sum() / total_ec)),
    mac("TierThreeMathPct", pct((ec.loc[ec["Tier"] == 3, "Field"] == "Mathematics").mean())),
    # 3. volume at low prestige each
    mac("SloanYr", "%.0f" % yw[sloan].sum()),
    mac("SloanPct", pct(yw[sloan].sum() / total_ec)),
    mac("BulkPrizes", int(bulk.sum())),
    mac("BulkYr", "%.0f" % yw[bulk].sum()),
    mac("BulkPct", pct(yw[bulk].sum() / total_ec)),
    mac("RestPrizes", int((~bulk).sum())),
    mac("RestYr", "%.0f" % yw[~bulk].sum()),
    mac("SingleWinner", int((yw <= 1).sum())),
    mac("SingleWinnerPct", pct((yw <= 1).mean())),
    mac("MedianYearlyWinners", "%.0f" % yw.median()),
    mac("MainMedianYearlyWinners", "%.1f" % main["Yearly Winners"].median()),
    mac("MainMaxYearlyWinners", "%.0f" % main["Yearly Winners"].max()),
]
for field, r in by_field.iterrows():
    key = "".join(ch for ch in field.title() if ch.isalpha())
    lines.append(mac("Prizes" + key, int(r["prizes"])))
    lines.append(mac("EventsPct" + key, "%.0f" % r["events_share_pct"]))

with open(os.path.join(TABLES, "r2_9_ec_macros.tex"), "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines) + "\n")
print("EC prizes %d | events/yr %.0f vs main %.0f | median views %.1f vs %.1f"
      % (len(ec), total_ec, total_main, ec_views.median(), main_median_views))
print("wrote r2_9_ec_macros.tex")
